### PR TITLE
Fixed bug where attachments didn't load on challenge creation

### LINKED ISSUE #91: Attachments not appearing to the challenge interface
Adding an attachment in the `Attachment` interface does not make it available in the `Challenge` creation interface.

### PR DESCRIPTION
**Pull request by zwade**
[Resolves #91] Needed to explicitly update attachment list

### CODE REVIEW

File: static/js/controllers/admin/challenges.js [hunk 1]
```diff
@@ -500,12 +500,16 @@ adminChallengeCtrls.controller('AdminChallengeCtrl', [
       $scope.attachmentType = 'new';
 
       attachService.get(function(data) {
+        console.log(data)
```
Comment (k9delight) [inline static/js/controllers/admin/challenges.js]: debug statements
